mbbill/undotree

README.md

Having quotes, either single or double, prevents persistent undo from working. This is to complete the recommendation in #21.

Remove quotes from undodir variable in README.

---

plugin/undotree.vim

I noticed that my statusline doesn't update properly when using undotree to move between revisions of a file (https://github.com/wincent/wincent/issues/16). I established that this was because it was using `'eventignore'` to suppress all autocmds, which in turn prevents the statusline from updating.
Commenting out the `set eventignore=all` line makes the failure to update go away, at the cost of firing more autocmds.
I considered adding an option for opting out of this behavior (eg. `let g:Undotree_Eventignore=0` or something), or rearchitecting my statusline to use an approach like vim-airline does based on CursorMoved autocmds (see https://github.com/vim-airline/vim-airline/issues/82; see also https://github.com/vim-airline/vim-airline/blob/30f078daf569e7d5e4f7829e39316387af349b41/plugin …

Suppress autocmds less aggressively

---

plugin/undotree.vim

Lot of space is wated by times indicator and the keyword ago.
We present here a new option for short timestamp : 
``` vim
let g:undotree_ShortIndicators=1
```
It will replace 
(5 seconds ago)
(1 minute ago) 
(2 minutes ago)
(1 hour ago)
(Original)   
by 
(5 s)
(1 m) 
(2 m) 
(1 h)
(Orig)   
and use a small panel size by default.

Option for shorter timestamp

---

README.md

The old link to the Bitbucket site just redirected me to https://bitbucket.org/product

Fix broken link to gundo project site in README

---

autoload/undotree.vim

Hello,
The error `E11` may be raised when one of these commands is executed in the command-line window (opened by pressing `q:`, `q/` or `q?`):
UndotreeToggle
UndotreeHide
UndotreeShow
UndotreeFocus
When that happens, it may have side-effects and give a long stack trace of errors.  
This PR tries to catch the error.
If you want me to change something, let me know, and if you don't like the changes, feel free to close the PR.
Thank you very much for your plugin.

Fix E11 error raised from command-line window

---

autoload/undotree.vim

Hello,
Currently, all functions are defined without the abort argument.
This PR tries to add it to each of them.
Thank you very much for your plugin.

Make functions abort immediately when an error is raised

---

doc/undotree.txt

Hello,
It seems [this commit](https://github.com/mbbill/undotree/commit/a80159c9f5c238575b63984b8bc610bc5de6b233) has broken some of the `<plug>` mappings documented at `:h Undotree_CustomMap`.
This PR tries to update the documentation to reflect the new `<plug>` mappings to use to go through the history of old saved states of the buffer.
Thank you very much for your plugin.

Update custom mappings in documentation

---

autoload/undotree.vim
doc/undotree.txt
plugin/undotree.vim

Adding configuration option `g:undotree_TreeVertShape` that enables the user to set the pipe line used for rendering the tree. This partially solves #103.
IMHO using '│' rather than a pipe '|' looks better because it fills the whole rectangle.
This breaks the highlighting in syntax, however this is also true for the configuration option `g:undotree_TreeNodeShape`. Do you have an idea on how to solve this @mbbill ? Should I submit an issue?

Adding the option for changing vertical shape in tree render

---

README.md

There was issues in README.md example:
- set undodir, instead of let
- wrong quotes after $HOME
- wrong dot after $HOME
[source](https://sidneyliebrand.io/blog/vim-tip-persistent-undo)

Fix set undodir. Add script to create dir if no exists

---

README.md

Fix set undodir, for vim options, use dedicated syntax
1. let undodir=target_path, It doesn't work. It uses the working directory.
2. For vim options(e.g. undodir), use dedicated syntax (:help :let-& ), it works.

Fix set undodir, use dedicated syntax

---

autoload/undotree.vim

First of all, thank you for making this plugin. This is a great plugin to visualize the undo sequence.
When I tried to learn how this plugin works, I noticed that there's a tab character and the lack of modeline in autoload file.
Referencing to plugin file and syntax file, I assumed you prefer four spaces so I replaced the tabs character with four spaces. I also added the modeline in autoload file too.

style(autoload): replace tabs with spaces and add modeline

---

autoload/undotree.vim

Problem: eventignore is not restored when there is no target window.
This happens when Undotree is used on non-normal buffers (buftype is not
empty or acwrite).
Solution: Set eventignore only after finding the target window, so that
it doesn't need to be restored in such cases.

Set eventignore after finding target window

---

autoload/undotree.vim

In clearing undo history, the target buffer's `&modified` status is set unexpectedly.
It modifies the file (`norm! a \<BS>\<Esc>`) to refresh undo history
(Probably it keeps the existing history data without any modification).
```vim
"In s:undotree.ActionClearHistory()
let ul_bak = &undolevels
let &undolevels = -1
call s:exec("norm! a \<BS>\<Esc>")
let &undolevels = ul_bak
```
But this turns `&modified` status on.
So it should backup `&modified` status besides `undolevels`.
1. Open and edit a file
2. Save the file
- Now `&modified` is not set
3. Push `[F5]` to open UndoTree window
4. Push `[C]` to clear history
- Input `YES` to the confirmation
5. Now the file's `&modified` status is set

Keep `&modified` status in clearing undo history

---

autoload/undotree.vim

Without Undotree, Vim's default behavior upon undoing or redoing a change in the current buffer is to open any folds that contain that change so that the change is visible. This behavior is controlled by the `undo` option in `&fdo`, which is enabled by default. Undotree is currently keeping such folds closed when undoing and redoing changes from the Undotree panel, which ultimately hides the changes that are being undone or redone.
This commit:
* Brings Undotree's behavior in line with how undo/redo usually works (e.g. when using `u` or `CTRL-R` in the current buffer)
* Let's you view undo/redo changes in real time and without having to open or disable folds first, even if those changes that you are undoing/redoing (from the Undotree panel) are currently hidden in closed folds
* Respects …

fix: make undoing/redoing changes in folds visible

---

autoload/undotree.vim

- The undofile will only be created once the buffer has been written to the file. Therefore, it is necessary to write the buffer the first time the :UndotreePersistUndo command is called.
- Echo  "A persistence undo file has been created." once the persistence undofile has been created.
- Add debug logging in the undotree#UndotreePersistUndo function.

Improve nvim/vim to immediately create the undofile after :UndotreePersistUndo executed.

---

doc/undotree.txt

I just noticed that I forgot to add the link ref to the undotree_UndoDir in the doc/undotree.txt file. :)

Fix undefined help link to undotree_UndoDir.

---

autoload/undotree.vim
plugin/undotree.vim

The utilization of the text concatenation operator `..` and the implementation of a default value for a function have resulted in errors in VIM versions prior to 8.0.2. Therefore, I switch to the operator `.` instead and remove the default parameter value definition.

Fix the use of .. has causes errors in VIM versions < 8.0.2.

---

autoload/undotree.vim

The plugin would fail regardless of the value of `g:undotree_DiffCommand` if `diff` did not exist. This patch removes this dependency.

Fix hardcoded 'diff' dependency

---

plugin/undotree.vim

When I was looking at the source code for undotree, I noticed that `-n` was used within user commands.  I failed to find what this was anywhere within vim documentation or online.  As such, I looked at the vim source code.  It seems to be an undocumented "feature" where the prefix of these "context setters"/"attributes" get promoted.
I feel that using the proper name for this attribute (`-nargs`) instead of the smallest valid prefix (`-n`) would help with the readability of the source code, especially since this is an undocumented "feature" (unlike commands, which show their valid abbreviations in the helpdocs, i.e. `:g[lobal]`).
*Alternatively, every `-n=0` could be omitted entirely, since `0` is the default value (according to the helpdocs).*

Clarify '-n' in user commands

---

README.md

The line number pointing to the options documentation was incorrect in the link (probably outdated from README changes). This PR fixes the line number in the link.
Thanks!

fix: Update line number to options doc in README

---

autoload/undotree.vim

If the path to the "undodir" would contain spaces, the plugin would report an error and the variable would not be set.

FIX: Setting the variable "undodir".

---

autoload/undotree.vim

Could you ignore `matchdelete()` error not to abort there,
in case accidentally the target match ID has already gone?

Ignore `matchdelete()` error

---

autoload/undotree.vim
doc/undotree.txt

Often, i find myself wanting to glance at undo diff beyond a single level. 
This PR adds additional functionality to add a custom marker for the diff view.
With diff marker set, the diff panel displays diff between current seq and marked seq.
Keymaps:
`=` - Toggles marker
`C` - Clears marker
Preview:

Add support for custom diff marker

---

autoload/undotree.vim
doc/undotree.txt
plugin/undotree.vim

Currently, the value of the signs displayed in the gutter of modified, deleted or added lines are hardcoded [here](https://github.com/mbbill/undotree/blob/b951b87b46c34356d44aa71886aecf9dd7f5788a/autoload/undotree.vim#L106).
This PR adds 4 options, to grant the user the ability to change them.
I called them undotreeSignAdded, undotreeSignChanged, undotreeSignDeleted and undotreeSignDeletedEnd, and their defaults are the same as they are now.

feat: add options to modify the symbols displayed in the gutter

---

autoload/undotree.vim
doc/undotree.txt
plugin/undotree.vim

Sometimes, plugins create buffers without assigning `buftype=nofile` or `buftype=nowrite` or similar; and undotree will track those, sometimes causing issues. The user should be able to disable this plugin for chosen filetypes, which is implemented by this PR.

feat: add undotree_DisabledFiletypes option

---

autoload/undotree.vim
doc/undotree.txt
plugin/undotree.vim

Currently, the plugin sets the `statusline` option when entering an Undotree buffer. This PR adds an option called undotree_StatusLine, which, when set to 0, will disable this, enabling the user to override it with another statusline.

feat: add undotree_StatusLine option
